name: '🐛 Bug Report'
description: 'Report an bug'
title: '[Bug] '
labels: ['🐛 Bug']
assignees: 
  - baijiangjie
body:
  - type: input
    attributes:
      label: 'Version'
      description: Versions prior to v2.28 are no longer supported.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 'Edition'
      options:
        - label: 'Community Edition'
        - label: 'Enterprise Edition'
        - label: 'Enterprise Trial Edition'
    validations:
      required: true
    
  - type: checkboxes
    attributes:
      label: 'Installation'
      options:
        - label: 'Online (Install using the curl command to download script quick_start.sh)'
        - label: 'Offline package'
        - label: 'All-in-One'
        - label: '1Panel'
        - label: 'Kubernetes'
        - label: 'Source Code'

  - type: textarea
    attributes:
      label: 'Environment'
      description: Describe your environment information in detail here, such as, operating system, browser, and deployment architecture, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: '🐛 Bug Description'
      description:
        Please provide a detailed description of the bug.<br/>
        Simple bug descriptions will not be considered. Please ensure to provide enough details and information to support the reproduction and fixing of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 'Recurrence Steps'
      description: Please provide detailed reproduction steps.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 'Attempted Solutions'
      description: If you have already tried to solve the problem, list the solutions you have tried here.
