name: '🤔 Question'
description: 'Pose a question'
title: '[Question] '
labels: ['🤔 Question']
assignees: 
  - baijiangjie
body:
  - type: input
    attributes:
      label: 'Version'
      description: Versions prior to v2.28 are no longer supported.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 'Edition'
      options:
        - label: 'Community Edition'
        - label: 'Enterprise Edition'
        - label: 'Enterprise Trial Edition'
    validations:
      required: true
    
  - type: checkboxes
    attributes:
      label: 'Installation'
      options:
        - label: 'Online (Install using the curl command to download script quick_start.sh)'
        - label: 'Offline package'
        - label: 'All-in-One'
        - label: '1Panel'
        - label: 'Kubernetes'
        - label: 'Source Code'

  - type: textarea
    attributes:
      label: 'Environment'
      description: Describe your environment information in detail here, such as, operating system, browser, and deployment architecture, etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Attempted Solutions'
      description: If you have already tried to solve the problem, list the solutions you have tried here.
